<?xml version="1.0" encoding="UTF-8"?><testrun name="ListaTest" project="lista_circular" tests="1" started="1" failures="1" errors="0" ignored="0">
  <testsuite name="application.ListaTest" time="0.0" displayname="ListaTest" uniqueid="[engine:junit-jupiter]/[class:application.ListaTest]">
    <testcase name="testImprimirVazia" classname="application.ListaTest" time="0.0" displayname="testImprimirVazia()" uniqueid="[engine:junit-jupiter]/[class:application.ListaTest]/[method:testImprimirVazia()]">
      <failure>
        <expected>lista vazia</expected>
        <actual>lista circular vazia</actual>
        org.opentest4j.AssertionFailedError: expected: &lt;lista vazia&gt; but was: &lt;lista circular vazia&gt;&#13;
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)&#13;
	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)&#13;
	at org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)&#13;
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:182)&#13;
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:177)&#13;
	at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:1145)&#13;
	at application.ListaTest.testImprimirVazia(ListaTest.java:15)&#13;
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)&#13;
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)&#13;
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)&#13;
&#13;

      </failure>
    </testcase>
  </testsuite>
</testrun>
